export interface Workspace {
  id: string;
  name: string;
  created_at: string;
}

export interface Post {
  id: string;
  workspace_id: string;
  platform: "instagram" | "facebook" | "tiktok" | "youtube";
  username: string;
  content: string;
  likes: number;
  comments: number;
  shares: number;
  timestamp: string;
  sentiment: "positive" | "neutral" | "negative";
  reach?: number;
}

export const initialWorkspaces: Workspace[] = [
  { id: "ws-global", name: "SocialPulse AI (Global)", created_at: "2026-01-15T08:00:00Z" },
  { id: "ws-acme", name: "Acme Corp (Retail)", created_at: "2026-03-10T14:30:00Z" },
  { id: "ws-apex", name: "Apex Agency", created_at: "2026-04-22T09:15:00Z" },
];

export const initialPosts: Post[] = [
  // --- Workspace: Global ---
  {
    id: "post-1",
    workspace_id: "ws-global",
    platform: "instagram",
    username: "tech_influencer",
    content: "Just tried the new AI assistant tool from SocialPulse and I am absolutely blown away by the speed and features! #AI #Innovation #Tech",
    likes: 1204,
    comments: 42,
    shares: 18,
    timestamp: "2026-05-30T12:00:00Z",
    sentiment: "positive",
    reach: 15000,
  },
  {
    id: "post-2",
    workspace_id: "ws-global",
    platform: "tiktok",
    username: "charlie_creative",
    content: "This new platform makes content scheduling and keyword monitoring so effortless. Highly recommend to creators! 🚀✨",
    likes: 5400,
    comments: 218,
    shares: 412,
    timestamp: "2026-05-29T18:30:00Z",
    sentiment: "positive",
    reach: 48000,
  },
  {
    id: "post-3",
    workspace_id: "ws-global",
    platform: "facebook",
    username: "john_doe_business",
    content: "The reporting functionality is quite disappointing. It crashed twice when trying to export our monthly CSV. Hope they fix this delay.",
    likes: 42,
    comments: 15,
    shares: 3,
    timestamp: "2026-05-28T09:15:00Z",
    sentiment: "negative",
    reach: 1200,
  },
  {
    id: "post-4",
    workspace_id: "ws-global",
    platform: "youtube",
    username: "digital_marketing_pro",
    content: "Detailed walkthrough of the SocialPulse AI dashboard. The sentiment analysis is decent, but keyword filters could use some enhancements.",
    likes: 850,
    comments: 64,
    shares: 128,
    timestamp: "2026-05-27T15:00:00Z",
    sentiment: "neutral",
    reach: 22000,
  },
  {
    id: "post-5",
    workspace_id: "ws-global",
    platform: "instagram",
    username: "design_weekly",
    content: "In love with the clean dark UI design! Reminds me of Vercel and Linear. Beautiful micro-interactions on the chart views.",
    likes: 912,
    comments: 19,
    shares: 7,
    timestamp: "2026-05-26T11:45:00Z",
    sentiment: "positive",
    reach: 9800,
  },
  {
    id: "post-6",
    workspace_id: "ws-global",
    platform: "tiktok",
    username: "meme_master",
    content: "When you try to run sentiment analysis and the AI tells you that your memes are neutral. I am offended! 😂",
    likes: 12800,
    comments: 542,
    shares: 980,
    timestamp: "2026-05-25T20:10:00Z",
    sentiment: "neutral",
    reach: 120000,
  },
  {
    id: "post-7",
    workspace_id: "ws-global",
    platform: "youtube",
    username: "saas_guy",
    content: "Why is the enterprise subscription price so expensive? 299 dollars/month is a bit too much for small agencies.",
    likes: 310,
    comments: 89,
    shares: 12,
    timestamp: "2026-05-24T14:22:00Z",
    sentiment: "negative",
    reach: 8500,
  },
  {
    id: "post-8",
    workspace_id: "ws-global",
    platform: "facebook",
    username: "marketing_agency_direct",
    content: "We connected all client channels (IG, FB, YouTube) in under 5 minutes. Real-time updates have been flawless so far.",
    likes: 188,
    comments: 24,
    shares: 16,
    timestamp: "2026-05-23T10:05:00Z",
    sentiment: "positive",
    reach: 3400,
  },
  {
    id: "post-9",
    workspace_id: "ws-global",
    platform: "instagram",
    username: "sara_reviews",
    content: "The support response is delayed. I submitted an API key issue yesterday and still no response from the team.",
    likes: 15,
    comments: 7,
    shares: 0,
    timestamp: "2026-05-22T08:30:00Z",
    sentiment: "negative",
    reach: 500,
  },
  {
    id: "post-10",
    workspace_id: "ws-global",
    platform: "tiktok",
    username: "dance_viral",
    content: "Analyzing viral trends with SocialPulse. The platform keyword comparison charts make it easy to spot what is trending next.",
    likes: 15300,
    comments: 290,
    shares: 610,
    timestamp: "2026-05-21T17:40:00Z",
    sentiment: "positive",
    reach: 110000,
  },

  // --- Workspace: Acme Corp ---
  {
    id: "post-acme-1",
    workspace_id: "ws-acme",
    platform: "instagram",
    username: "acme_shopper",
    content: "Purchased the new Acme eco-friendly water bottle. It looks great but the cap is leaking slightly. #AcmeLiving",
    likes: 340,
    comments: 28,
    shares: 2,
    timestamp: "2026-05-30T10:15:00Z",
    sentiment: "neutral",
    reach: 4500,
  },
  {
    id: "post-acme-2",
    workspace_id: "ws-acme",
    platform: "tiktok",
    username: "eco_fashionista",
    content: "Unboxing my Acme eco-package! 100% biodegradable and zero waste packaging. We need more brands to do this! 🌿💚",
    likes: 9200,
    comments: 114,
    shares: 205,
    timestamp: "2026-05-29T16:00:00Z",
    sentiment: "positive",
    reach: 65000,
  },
  {
    id: "post-acme-3",
    workspace_id: "ws-acme",
    platform: "facebook",
    username: "angry_customer",
    content: "Terrible customer service. Ordered next-day delivery on Acme shoes and it arrived 5 days late with no apology.",
    likes: 54,
    comments: 32,
    shares: 8,
    timestamp: "2026-05-28T13:40:00Z",
    sentiment: "negative",
    reach: 1500,
  },
  {
    id: "post-acme-4",
    workspace_id: "ws-acme",
    platform: "youtube",
    username: "tech_tear_down",
    content: "Acme Smart Thermostat review after 30 days. Easy installation but the app loses connection occasionally.",
    likes: 1200,
    comments: 98,
    shares: 45,
    timestamp: "2026-05-27T19:00:00Z",
    sentiment: "neutral",
    reach: 32000,
  },
  {
    id: "post-acme-5",
    workspace_id: "ws-acme",
    platform: "instagram",
    username: "design_lover",
    content: "The aesthetic of Acme retail stores is unmatched. Concrete panels and soft warm lighting. Minimalist perfection.",
    likes: 550,
    comments: 12,
    shares: 9,
    timestamp: "2026-05-25T11:00:00Z",
    sentiment: "positive",
    reach: 5200,
  },
  {
    id: "post-acme-6",
    workspace_id: "ws-acme",
    platform: "tiktok",
    username: "kitchen_hacks",
    content: "Acme blending tool vs standard blender test. Acme absolutely crushed it, and it makes zero noise! 🤫🍓",
    likes: 18400,
    comments: 312,
    shares: 1100,
    timestamp: "2026-05-23T21:30:00Z",
    sentiment: "positive",
    reach: 160000,
  },
  {
    id: "post-acme-7",
    workspace_id: "ws-acme",
    platform: "facebook",
    username: "concerned_citizen",
    content: "Acme factory expansion near our neighbourhood is raising concern about noise levels. Hope they communicate more with locals.",
    likes: 112,
    comments: 65,
    shares: 24,
    timestamp: "2026-05-20T08:15:00Z",
    sentiment: "negative",
    reach: 3500,
  },

  // --- Workspace: Apex Agency ---
  {
    id: "post-apex-1",
    workspace_id: "ws-apex",
    platform: "instagram",
    username: "apex_partner",
    content: "Incredible launch event tonight! Shoutout to the Apex Agency team for executing this campaign flawlessly.",
    likes: 480,
    comments: 19,
    shares: 15,
    timestamp: "2026-05-29T22:00:00Z",
    sentiment: "positive",
    reach: 6000,
  },
  {
    id: "post-apex-2",
    workspace_id: "ws-apex",
    platform: "youtube",
    username: "marketing_insider",
    content: "How Apex Agency scaled a local skincare brand to 1M dollars in sales in under 6 months. High value case study.",
    likes: 2400,
    comments: 182,
    shares: 320,
    timestamp: "2026-05-28T16:00:00Z",
    sentiment: "positive",
    reach: 48000,
  },
  {
    id: "post-apex-3",
    workspace_id: "ws-apex",
    platform: "tiktok",
    username: "brand_critic",
    content: "Wait, did Apex Agency copy that billboard design from the 90s campaign? The similarity is uncanny...",
    likes: 1350,
    comments: 72,
    shares: 140,
    timestamp: "2026-05-27T12:00:00Z",
    sentiment: "negative",
    reach: 12000,
  },
];
